---
- name: "Add the apt-repo with later version of python"
  become: yes
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    update_cache: yes

- name: "Install alternative python"
  become: yes
  apt:
    name: "python{{python_alternative_version}}"

- name: "Update alternatives"
  become: yes
  shell: "update-alternatives --install /usr/bin/python3 python3 /usr/bin/python{{python_alternative_version}} 2"

- name: "Setup python"
  become: yes
  shell: "update-alternatives --config python3"

# This will install python 3.5, but it will also setup the system environment properly for pip3.
- name: "Setup pip3"
  apt:
    name: "python3-pip"

- name: "Make sure we are on the latest version of pip"
  pip:
    name: "pip"
    state: "present"
    version: "{{python_pip_version}}"
    executable: "pip3"
